#!/usr/bin/env node
var Player = require('mpris-service');

process.stdin.on('data', function(data) {
  try {
    var obj = JSON.parse(data);
    if (obj.event === 'playing') {
      player.metadata = {
        'mpris:trackid': player.objectPath('track/0'),
        'mpris:length': 60 * 1000 * 1000, // In microseconds
        'mpris:artUrl': 'http://www.adele.tv/images/facebook/adele.jpg',
        'xesam:title': obj.tabTitle,
        'xesam:album': obj.subsystem,
        'xesam:artist': obj.url
      };

      player.playbackStatus = 'Playing';
    }
  } catch (e) {
  } finally {
    process.stdout.write(data);
  }
});

process.stdin.on('end', () => {
  process.stdout.end();
});

var player = Player({
  name: 'nodejs',
  identity: 'Node.js media player',
  supportedUriSchemes: ['file'],
  supportedMimeTypes: ['audio/mpeg', 'application/ogg'],
  supportedInterfaces: ['player']
});

// Events
var events = [
  'raise',
  'quit',
  'next',
  'previous',
  'pause',
  'playpause',
  'stop',
  'play',
  'seek',
  'position',
  'open',
  'volume'
];
events.forEach(function(eventName) {
  player.on(eventName, function() {
    console.log('Event:', eventName, arguments);
  });
});

player.on('quit', function() {
  process.exit();
});
